### PR TITLE
Libwally compatibility

### PR DESCRIPTION
**Pull request by gorazdko**
## Abstract

Required by https://github.com/BlockchainCommons/bc-lethekit/pull/49

### CODE REVIEW

**Comment by ChristopherA** [comment]
@wolfmcnally Can you do first pass on reviewing thing PR?

**Comment by ChristopherA** [comment]
@wolfmcnally ??

**Comment by wolfmcnally** [comment]
@gorazdko It looks like you just duplicated a method and changed its name? What is the purpose of so much duplicated code? How does it resolve Arduino compatibility?

@ChristopherA

**Comment by gorazdko** [comment]
>@gorazdko It looks like you just duplicated a method and changed its name? What is the purpose of so much duplicated code? How does it resolve Arduino compatibility?

As described in https://github.com/BlockchainCommons/bc-lethekit/pull/49 the problem is a function definition clash. There is a function with the same name in libwally exposed in include folder.

I know this is an ugly fix, but I think this library should give way to libwally. I think the next step is for bc-lethekit to refactor bip39 code with libwally and deprecate bc-bip39.

I'm happy to take other suggestions.

**Comment by gorazdko** [comment]
Closing this in favor of https://github.com/BlockchainCommons/bc-lethekit/pull/49/commits/b3c5ef56f186b8f8cb556a1224dc6cc9b2f1eb94
  * I deleted bip39 from libwally wrappers

**Pull request closed without merging**
